version: "2"

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - /mnt/nginx1/html:/usr/share/nginx/html
      - /mnt/nginx1/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=miguelsantana.com
      - NGINX_PORT=80
    restart: always